### ISSUE TITLE
a new request

### ISSUE THREAD

**Issue by maravento** [gryf/vboxmanage-bash-completion#12]
great project. a request:
You could consider, if it is not very complicated, incorporate commands to create virtual disks for data storage (vdi), format them (ext4, ntfs, etc), mount and unmount them in linux. This is something that is only partially in the VBoxManager documentation and there is little information about these procedures

thanks in advanced

**Comment by gryf** [comment]
Hi.

Unfortunately, this is mostly outside of `vboxmanage` command responsibility - since you'll need to have tools to create disk image, create and format partitions - perhaps with elevated permissions. This is totally outside of this little project which merely provides completion for the `vboxmanage` command.

As for mounting, there is separate tool called `vboximg-mount`.
